Add SDK + UX Fixes for End-to-End DDR
cionicwear/EndlessRevolution pull request #1
Opened 2020-04-06 23:49 UTC by tosmith97

* Added cionic SDK + custom listeners for IMU and EMG predictions
* Game ends when the song ends
* Constant speed throughout the game (1 arrow every 2 seconds)
*Currently supports 1 song/difficulty
![image](https://user-images.githubusercontent.com/15066974/78614845-a32ccf00-7824-11ea-8b1c-1e8a97d77245.png)

2020-04-07 00:25 UTC, dachelis commented
BEATUFUL!

2020-04-07 18:06 UTC, ray-ray requested changes
Did you intentionally comment out the monitor code?

2020-04-07 18:06 UTC, ray-ray commented on lib/bundle.js
> +  // const monitorAPI = new cionicjs.MonitorAPI({});
No monitor?

2020-04-07 18:24 UTC, tosmith97 commented
> Did you intentionally comment out the monitor code?

Yeah I usually comment out monitor code during local testing, otherwise it clogs the console with a bunch of 404s/403s

2020-04-09 19:53 UTC, ray-ray approved these changes

2020-04-13 17:25 UTC, merged